### ISSUE TITLE
Knitting results in lack of spatial constance error? (Erroneous duplicate in /Scratchwork)

### ISSUE THREAD

**Issue by ccsteinhardt** [sds192-i21/mp4#1] opened 2021-02-07 22:57 UTC
``` r
library(tidyverse)
library(sf)
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1
library(macleish)
#> Loading required package: etl

url <- "http://download.massgis.digital.mass.gov/shapefiles/contours5k/hp337.zip"
local_file <- basename(url)
download.file(url, destfile = local_file)
unzip(local_file, exdir = "contours5k")

dsn <- path.expand("contours5k")
dsn
#> [1] "contours5k"
list.files(dsn)
#> [1] "hp337.dbf"     "hp337.prj"     "hp337.sbn"     "hp337.sbx"    
#> [5] "hp337.shp"     "hp337.shp.xml" "hp337.shx"

st_layers(dsn)
#> Driver: ESRI Shapefile 
#> Available layers:
#>   layer_name geometry_type features fields
#> 1      hp337   Line String     2684      4
contours5k <- read_sf(dsn)

contours5kcoord <- contours5k %>%
  st_transform(4326)

contours5kmacl <- contours5kcoord %>%
  st_intersection(boundary) %>%
  st_cast("MULTIPOINT") %>%
  st_cast("POINT")
#> Error in geos_op2_geom("intersection", x, y): st_crs(x) == st_crs(y) is not TRUE
```

<sup>Created on 2021-02-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
<img width="711" alt="Screen Shot 2021-02-07 at 1 35 07 PM" src="https://user-images.githubusercontent.com/76970361/107161918-dde42400-696d-11eb-866c-62a53f434eb7.png">

**Comment by beanumber** [comment] 2021-02-08 02:35
Duplicate of https://github.com/sds192-i21/sds192-i21-scratchwork/issues/2

**Closed as completed** 2021-02-08 02:34 UTC
